stages:
  - test

backend-tests:
  image: python:3.10-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 sales/api

frontend-tests:
  image: node:lts-bullseye
  stage: test
  script:
    - cd ghi/app
    - npm install
    - npm run lint
