# Generated by Django 5.0.7 on 2024-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="salesperson",
            name="employee_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
