# Generated by Django 5.0.7 on 2024-12-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0002_alter_customer_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(),
        ),
    ]
